AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Employees
      AttributeDefinitions:
        - AttributeName: surname
          AttributeType: S
        - AttributeName: name
          AttributeType: S
      KeySchema:
        - AttributeName: surname
          KeyType: HASH  # Partition key
        - AttributeName: name
          KeyType: RANGE # Sort key
      BillingMode: PAY_PER_REQUEST
